class Solution {
        public:
            int ladderLength(string beginWord, string endWord, vector<string>& wordList) {
                    // Create a set for O(1) lookup
                            unordered_set<string> wordSet(wordList.begin(), wordList.end());
                                    
                                            // If endWord is not in the list, impossible
                                                    if (wordSet.find(endWord) == wordSet.end()) {
                                                                return 0;
                                                                        }
                                                                                
                                                                                        // BFS queue: {word, level}
                                                                                                queue<pair<string, int>> q;
                                                                                                        q.push({beginWord, 1});
                                                                                                                
                                                                                                                        while (!q.empty()) {
                                                                                                                                    auto [currentWord, level] = q.front();
                                                                                                                                                q.pop();
                                                                                                                                                            
                                                                                                                                                                        // Try changing each character
                                                                                                                                                                                    for (int i = 0; i < currentWord.length(); i++) {
                                                                                                                                                                                                    char originalChar = currentWord[i];
                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    // Try all 26 lowercase letters
                                                                                                                                                                                                                                                    for (char c = 'a'; c <= 'z'; c++) {
                                                                                                                                                                                                                                                                        if (c == originalChar) continue;
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                // Create new word
                                                                                                                                                                                                                                                                                                                                    string nextWord = currentWord;
                                                                                                                                                                                                                                                                                                                                                        nextWord[i] = c;
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                // If we reached the endWord
                                                                                                                                                                                                                                                                                                                                                                                                                    if (nextWord == endWord) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            return level + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // If nextWord exists in wordSet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (wordSet.find(nextWord) != wordSet.end()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    wordSet.erase(nextWord);  // Mark as visited
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            q.push({nextWord, level + 1});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 0;  // No path found
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
}
