class Solution {
    public:
        bool isInterleave(string s1, string s2, string s3) {
                int n = s1.length();
                        int m = s2.length();
                                
                                        // Quick check: lengths must match
                                                if (n + m != s3.length()) {
                                                            return false;
                                                                    }
                                                                            
                                                                                    // dp[i][j] = can we form s3[0...i+j-1] using s1[0...i-1] and s2[0...j-1]
                                                                                            vector<vector<bool>> dp(n + 1, vector<bool>(m + 1, false));
                                                                                                    
                                                                                                            // Base case: empty strings
                                                                                                                    dp[0][0] = true;
                                                                                                                            
                                                                                                                                    // Fill first column (only using s1)
                                                                                                                                            for (int i = 1; i <= n; i++) {
                                                                                                                                                        dp[i][0] = dp[i-1][0] && (s1[i-1] == s3[i-1]);
                                                                                                                                                                }
                                                                                                                                                                        
                                                                                                                                                                                // Fill first row (only using s2)
                                                                                                                                                                                        for (int j = 1; j <= m; j++) {
                                                                                                                                                                                                    dp[0][j] = dp[0][j-1] && (s2[j-1] == s3[j-1]);
                                                                                                                                                                                                            }
                                                                                                                                                                                                                    
                                                                                                                                                                                                                            // Fill the rest of the table
                                                                                                                                                                                                                                    for (int i = 1; i <= n; i++) {
                                                                                                                                                                                                                                                for (int j = 1; j <= m; j++) {
                                                                                                                                                                                                                                                                // Check if we can take from s1
                                                                                                                                                                                                                                                                                bool fromS1 = dp[i-1][j] && (s1[i-1] == s3[i+j-1]);
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                // Check if we can take from s2
                                                                                                                                                                                                                                                                                                                                bool fromS2 = dp[i][j-1] && (s2[j-1] == s3[i+j-1]);
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                dp[i][j] = fromS1 || fromS2;
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                    return dp[n][m];
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        };
